import type { PartialBlock } from "@blocknote/core";
import type { Template } from "../types";

export const TEMPLATES: Template[] = [
  {
    key: "meeting",
    name: "Meeting Notes",
    icon: "🤝",
    description: "Capture agenda, discussion points, and action items",
    content: [
      { type: "heading", props: { level: 1 }, content: [{ type: "text", text: "Meeting Notes", styles: {} }] },
      { type: "paragraph", content: [{ type: "text", text: "📅 Date: ", styles: { bold: true } }, { type: "text", text: new Date().toLocaleDateString(), styles: {} }] },
      { type: "heading", props: { level: 2 }, content: [{ type: "text", text: "Agenda", styles: {} }] },
      { type: "bulletListItem", content: [{ type: "text", text: "Topic 1", styles: {} }] },
      { type: "bulletListItem", content: [{ type: "text", text: "Topic 2", styles: {} }] },
      { type: "heading", props: { level: 2 }, content: [{ type: "text", text: "Discussion", styles: {} }] },
      { type: "paragraph", content: [{ type: "text", text: "Key points discussed…", styles: {} }] },
      { type: "heading", props: { level: 2 }, content: [{ type: "text", text: "Action Items", styles: {} }] },
      { type: "checkListItem", props: { checked: false }, content: [{ type: "text", text: "Assign owners", styles: {} }] },
      { type: "checkListItem", props: { checked: false }, content: [{ type: "text", text: "Set deadlines", styles: {} }] },
    ] as PartialBlock[],
  },
  {
    key: "daily",
    name: "Daily Journal",
    icon: "☀️",
    description: "Reflect on your day — gratitude, goals, notes",
    content: [
      { type: "heading", props: { level: 1 }, content: [{ type: "text", text: new Date().toLocaleDateString("en-US", { weekday: "long", month: "long", day: "numeric" }), styles: {} }] },
      { type: "heading", props: { level: 2 }, content: [{ type: "text", text: "🙏 Grateful for", styles: {} }] },
      { type: "bulletListItem", content: [{ type: "text", text: "", styles: {} }] },
      { type: "heading", props: { level: 2 }, content: [{ type: "text", text: "🎯 Today's focus", styles: {} }] },
      { type: "checkListItem", props: { checked: false }, content: [{ type: "text", text: "", styles: {} }] },
      { type: "heading", props: { level: 2 }, content: [{ type: "text", text: "📝 Notes", styles: {} }] },
      { type: "paragraph", content: [{ type: "text", text: "", styles: {} }] },
      { type: "heading", props: { level: 2 }, content: [{ type: "text", text: "💭 End of day reflection", styles: {} }] },
      { type: "paragraph", content: [{ type: "text", text: "", styles: {} }] },
    ] as PartialBlock[],
  },
  {
    key: "project",
    name: "Project Plan",
    icon: "🚀",
    description: "Outline goals, milestones, and tasks for a project",
    content: [
      { type: "heading", props: { level: 1 }, content: [{ type: "text", text: "Project Plan", styles: {} }] },
      { type: "heading", props: { level: 2 }, content: [{ type: "text", text: "Overview", styles: {} }] },
      { type: "paragraph", content: [{ type: "text", text: "What are we building and why?", styles: {} }] },
      { type: "heading", props: { level: 2 }, content: [{ type: "text", text: "Goals", styles: {} }] },
      { type: "bulletListItem", content: [{ type: "text", text: "Goal 1", styles: {} }] },
      { type: "bulletListItem", content: [{ type: "text", text: "Goal 2", styles: {} }] },
      { type: "heading", props: { level: 2 }, content: [{ type: "text", text: "Milestones", styles: {} }] },
      { type: "numberedListItem", content: [{ type: "text", text: "Phase 1 — ", styles: {} }] },
      { type: "numberedListItem", content: [{ type: "text", text: "Phase 2 — ", styles: {} }] },
      { type: "heading", props: { level: 2 }, content: [{ type: "text", text: "Tasks", styles: {} }] },
      { type: "checkListItem", props: { checked: false }, content: [{ type: "text", text: "Task 1", styles: {} }] },
      { type: "checkListItem", props: { checked: false }, content: [{ type: "text", text: "Task 2", styles: {} }] },
      { type: "heading", props: { level: 2 }, content: [{ type: "text", text: "Risks", styles: {} }] },
      { type: "paragraph", content: [{ type: "text", text: "Potential blockers and mitigations…", styles: {} }] },
    ] as PartialBlock[],
  },
  {
    key: "bugreport",
    name: "Bug Report",
    icon: "🐛",
    description: "Document a bug with steps to reproduce and expected behavior",
    content: [
      { type: "heading", props: { level: 1 }, content: [{ type: "text", text: "Bug Report", styles: {} }] },
      { type: "heading", props: { level: 2 }, content: [{ type: "text", text: "Summary", styles: {} }] },
      { type: "paragraph", content: [{ type: "text", text: "Brief description of the issue.", styles: {} }] },
      { type: "heading", props: { level: 2 }, content: [{ type: "text", text: "Steps to Reproduce", styles: {} }] },
      { type: "numberedListItem", content: [{ type: "text", text: "Step 1", styles: {} }] },
      { type: "numberedListItem", content: [{ type: "text", text: "Step 2", styles: {} }] },
      { type: "heading", props: { level: 2 }, content: [{ type: "text", text: "Expected Behavior", styles: {} }] },
      { type: "paragraph", content: [{ type: "text", text: "", styles: {} }] },
      { type: "heading", props: { level: 2 }, content: [{ type: "text", text: "Actual Behavior", styles: {} }] },
      { type: "paragraph", content: [{ type: "text", text: "", styles: {} }] },
      { type: "heading", props: { level: 2 }, content: [{ type: "text", text: "Environment", styles: {} }] },
      { type: "bulletListItem", content: [{ type: "text", text: "OS: ", styles: {} }] },
      { type: "bulletListItem", content: [{ type: "text", text: "Browser: ", styles: {} }] },
    ] as PartialBlock[],
  },
  {
    key: "reading",
    name: "Reading List",
    icon: "📚",
    description: "Track books, articles, and resources to read",
    content: [
      { type: "heading", props: { level: 1 }, content: [{ type: "text", text: "Reading List", styles: {} }] },
      { type: "heading", props: { level: 2 }, content: [{ type: "text", text: "📖 Currently Reading", styles: {} }] },
      { type: "bulletListItem", content: [{ type: "text", text: "", styles: {} }] },
      { type: "heading", props: { level: 2 }, content: [{ type: "text", text: "🔖 Up Next", styles: {} }] },
      { type: "bulletListItem", content: [{ type: "text", text: "", styles: {} }] },
      { type: "heading", props: { level: 2 }, content: [{ type: "text", text: "✅ Finished", styles: {} }] },
      { type: "bulletListItem", content: [{ type: "text", text: "", styles: {} }] },
      { type: "heading", props: { level: 2 }, content: [{ type: "text", text: "💡 Key Takeaways", styles: {} }] },
      { type: "paragraph", content: [{ type: "text", text: "", styles: {} }] },
    ] as PartialBlock[],
  },
  {
    key: "weekly",
    name: "Weekly Review",
    icon: "📅",
    description: "Reflect on the week and plan ahead",
    content: [
      { type: "heading", props: { level: 1 }, content: [{ type: "text", text: "Weekly Review", styles: {} }] },
      { type: "heading", props: { level: 2 }, content: [{ type: "text", text: "✅ What went well", styles: {} }] },
      { type: "bulletListItem", content: [{ type: "text", text: "", styles: {} }] },
      { type: "heading", props: { level: 2 }, content: [{ type: "text", text: "⚡ What to improve", styles: {} }] },
      { type: "bulletListItem", content: [{ type: "text", text: "", styles: {} }] },
      { type: "heading", props: { level: 2 }, content: [{ type: "text", text: "🎯 Next week's goals", styles: {} }] },
      { type: "checkListItem", props: { checked: false }, content: [{ type: "text", text: "", styles: {} }] },
    ] as PartialBlock[],
  },
];

export function getTemplate(key: string): Template | undefined {
  return TEMPLATES.find((t) => t.key === key);
}
